### ISSUE TITLE
On windows, include paths do not work as expected

### ISSUE THREAD

**Issue by DarioDeBastianiNektan** [stefanullinger/grunt-twig-render#10]
On mac/linux, including a file using e.g. `{% extends '../common/templates/index.twig' %}` works as intended: the path is resolved relative to the template being processed.

On windows, the path seems to be resolved relative to the Gruntfile, which means that while the above works fine everywhere else, it breaks when executed there.

**Comment by sullinger** [comment]
Hi! As grunt-twig-render is just a wrapper around twig.js and you are referencing the extends-tag in your issue, the problem seems to be an issue with twig.js itself, doesn't it?

**Comment by benceg** [comment]
+1, please accept SonicGD's pull request. :)

**Comment by stefanullinger** [comment]
Hi, I have now debugged this issue and found out that it indeed is related to twig.js.
See my pull-request here at https://github.com/justjohn/twig.js/pull/252

**Comment by benceg** [comment]
Thanks @stefanullinger! Looking forward to twig.js merging your PR.

**Comment by stefanullinger** [comment]
The PR has finally been merged into twig.js: https://github.com/justjohn/twig.js/pull/300
