### ISSUE TITLE
Enhancement and update version

### ISSUE THREAD

**Issue by Rodrigo-Ludgero** [stefanullinger/grunt-twig-render#12]
Install all dependencies inside a node_modules folder inside of grunt-twig-render folder, instead of installing on the root?

Can you update to the latest version of twig?

Thanks in advance. :+1:

**Comment by stefanullinger** [comment]
Hi, I've just released v1.7.3 that uses twig 0.8.8.

What do you mean by installing inside the grunt-twig-render directory? How do you do that? What's the benefit?

**Comment by Rodrigo-Ludgero** [comment]
Hi, thanks for the quick response :airplane: and update :smiley: 
> What do you mean by installing inside the grunt-twig-render directory? 

I was wrong thinking that had to do with installing the plugin, but I have seen figuring out which is the npm@3 new version behavior [http://blog.npmjs.org/post/110924823920/npm-weekly-5](url)

Once again, thank you very much per create and maintaining this plugin.
