### ISSUE TITLE
Cannot populate blocks

### ISSUE THREAD

**Issue by acjbizar** [stefanullinger/grunt-twig-render#20]
In my Gruntfile, I have:

    data: {
        body: 'Hello, World!',
        title: 'Hello, World!'
    },

In my Twig template, I have:

    <title>{{ title }}</title
    <body>
    {% block body %}{% endblock %}
    </body>

The `title` is populated as expected, but the `body` appears to fail silently. Are blocks not supported, or am I missing something?

**Comment by stefan-b314** [comment]
Hey @acjbizar, sorry – I have not worked on this project for a very long time. But I guess by `{% block body %}{% endblock %}` you are just giving the block the name "body", right?! You are not outputting anything.

**Comment by acjbizar** [comment]
Hi @stefanullinger, thanks for your reply. I totally forgot about this issue, but I guess you’re right. Looking at what I’m to do there, I think the following should work:

```twig
{% block body %}{{ block('body') }}{% endblock %}
```

I’m not going to bother testing it though. When I use Twig nowadays it’s usually in combination with Gulp and/or webpack, not Grunt. I’ll just go ahead and close this issue. Thanks for your time.
